# train_custom.yaml
# 'mode' is required only for CLI usage
mode: train
epochs: 200
project: /content/gdrive/MyDrive/my_phd/airport-trolley
data: /content/Airport-Trolley/data.yaml
name: smodel
imgsz: 640
hsv_h: 0.03
hsv_s: 0.6
hsv_v: 0.5
fliplr: 0.5
degrees: 90
shear: 10